name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Step to install yq
    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
        chmod +x /usr/bin/yq
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mbenadik/flaskapp:latest
    - name: push Docker image
      run: docker push mbenadik/flaskapp:latest
    - name: Pull helm Chart
      run: |
        git clone https://github.com/MarosBenadik/flask-helm.git
    - name: bump version
      run: |
        echo "Old Version: $( yq '.app.version' flask-helm/values.yaml ) "
        yq eval '
          .app.version |= (
            (split(".") | 
            .[0] as $major | .[1] as $minor | .[2] as $patch |
            if ($patch | tonumber) == 9 then
              if ($minor | tonumber) == 9 then
                ($major | tonumber + 1 | tostring) + ".0.0"
              else
                $major + "." + ($minor | tonumber + 1 | tostring) + ".0"
              end
            else
              $major + "." + $minor + "." + ($patch | tonumber + 1 | tostring)
            end
          ))' -i flask-helm/values.yaml
        echo "New Version: $( yq '.app.version' flask-helm/values.yaml ) "
    - name: commit version bump
      run: |
        cd flask-helm
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Updated config.yaml with new version"
        git push https://$GITHUB_TOKEN@github.com/MarosBenadik/flask-helm.git dev
        
      

        
